apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: resume-backend
  template:
    metadata:
      labels:
        app: resume-backend
    spec:
      containers:
      - name: resume-backend-container
        image: resume_backend
        ports:
        - containerPort: 8000